/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagIndexRouteImport } from './routes/tag/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as BlogBlogIdRouteImport } from './routes/blog/$blogId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagIndexRoute = TagIndexRouteImport.update({
  id: '/tag/',
  path: '/tag/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlogIdRoute = BlogBlogIdRouteImport.update({
  id: '/blog/$blogId',
  path: '/blog/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
  '/tag': typeof TagIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
  '/tag': typeof TagIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$blogId': typeof BlogBlogIdRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/tag/': typeof TagIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog/$blogId' | '/about' | '/blog' | '/tag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/$blogId' | '/about' | '/blog' | '/tag'
  id: '__root__' | '/' | '/blog/$blogId' | '/about/' | '/blog/' | '/tag/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogBlogIdRoute: typeof BlogBlogIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  TagIndexRoute: typeof TagIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/': {
      id: '/tag/'
      path: '/tag'
      fullPath: '/tag'
      preLoaderRoute: typeof TagIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$blogId': {
      id: '/blog/$blogId'
      path: '/blog/$blogId'
      fullPath: '/blog/$blogId'
      preLoaderRoute: typeof BlogBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogBlogIdRoute: BlogBlogIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  TagIndexRoute: TagIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
